version: "3.7"
services:
  db:
    image: mysql:8.0.28
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./config/nginx/proxy.conf.template:/etc/nginx/templates/proxy.conf.template
    depends_on:
      - backend
      - frontend
    environment:
      NGINX_HOST: ${PROJECT_NAME}
      NGINX_PORT: 8080
    ports:
      - 8080:8080

  backend: &backend_base
    stdin_open: true
    tty: true
    build: backend
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    environment:
      MYSQL_CONNECTION: ${MYSQL_CONNECTION}
      REDIS_CONNECTION: ${REDIS_CONNECTION}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b 0.0.0.0
  worker:
    <<: *backend_base
    command: bundle exec sidekiq
    ports: []

  frontend: &frontend_base
    build: frontend
    command: yarn dev
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "4000:4000"
  storybook:
    <<: *frontend_base
    build: frontend
    command: yarn storybook --ci
    depends_on:
      - frontend
    ports:
      - "6006:6006"

volumes:
  node_modules:
  mysql_data:
