version: "3.7"
services:
  db:
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5432:5432
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./config/nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    depends_on:
      - backend
      - frontend
    environment:
      VIRTUAL_HOST: atomicfarm
      VIRTUAL_PORT: 8080
    ports:
      - 8080:8080
  worker:
    build: backend
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
      SIDEKIQ_REDIS_URL: redis://redis:6379/1
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
  backend:
    stdin_open: true
    tty: true
    build: backend
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    environment:
      REDIS_URL: redis://redis:6379/0
      SIDEKIQ_REDIS_URL: redis://redis:6379/1
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b 0.0.0.0
  frontend:
    build: frontend
    depends_on:
      - backend
    command: yarn dev
    volumes:
      - ./frontend/:/app
      - node_modules:/app/node_modules
    ports:
      - "4000:4000"
volumes:
  node_modules:
  pg_data:
