version: "3.7"
services:
  db:
    image: mysql:8.0.28
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./config/nginx/proxy.conf.template:/etc/nginx/templates/proxy.conf.template
    depends_on:
      - backend
      - frontend
    environment:
      NGINX_HOST: ${PROJECT_NAME}
      NGINX_PORT: 8080
    ports:
      - 8080:8080
  worker:
    build: backend
    command: bundle exec sidekiq
    environment:
      MYSQL_CONNECTION: ${MYSQL_CONNECTION}
      REDIS_URL: redis://redis:6379/0
      SIDEKIQ_REDIS_URL: redis://redis:6379/1
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
  backend:
    stdin_open: true
    tty: true
    build: backend
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    environment:
      MYSQL_CONNECTION: ${MYSQL_CONNECTION}
      REDIS_URL: redis://redis:6379/0
      SIDEKIQ_REDIS_URL: redis://redis:6379/1
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b 0.0.0.0
  frontend:
    build: frontend
    depends_on:
      - backend
    command: yarn dev
    volumes:
      - ./frontend/:/app
      - node_modules:/app/node_modules
    ports:
      - "4000:4000"
volumes:
  node_modules:
  mysql_data:
